# Config file for automatic testing at travis-ci.org

language: python
matrix:
    include:
        - python: 3.3
          env: 
            - TOXENV=py33
        - python: 3.4
          env:
            - TOXENV=py34
        - python: 3.5
          env:
            - TOXENV=py35


# before_script:
#  - sudo apt install portaudio19-dev
#  - sudo apt install python-all-dev

addons:
  apt:
    packages:
    - portaudio19-dev
    - python3-all-dev

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U tox
  - pip install pyaudio

# command to run tests, e.g. python setup.py test
script: tox -e ${TOXENV}
