# Config file for automatic testing at travis-ci.org

language: python
python: 3.5

env:
  - TOXENV=py36
  - TOXENV=py35
#  - TOXENV=py34
#  - TOXENV=py33

# before_script:
#  - sudo apt install portaudio19-dev
#  - sudo apt install python-all-dev

addons:
  apt:
    packages:
    - portaudio19-dev
    - python3-all-dev

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U tox
  - pip install pyaudio

# command to run tests, e.g. python setup.py test
script: tox -e ${TOXENV}
